### PR TITLE
Added setup.py

### PR DESCRIPTION
**Pull request by petevg**
Makes it possible to add plugins as a depedency to another project (for
example, gh:juju-solutions/matrix, which is what prompted this
change).

The setup.py puts all the scripts in Python's bin dir, naturally adding
them to the path in your current Python environment.

@johnsca

### CODE REVIEW

**Comment by johnsca** [comment]
+1 this makes it easier to manage the path, though I'd also like to see this grow a snap.yaml as well.

**Comment by marcoceppi** [comment]
Why are people depending on plugins? It's not a viable long term decision.
Plugins are temporary play grounds for piloting features in juju.

**Comment by petevg** [comment]
@marcoceppi the cwr-ci bundle wants to run juju-crashdump in order to gather logs from a test run. @johnsca also wants to drop it into bundletester. It's a useful bit of functionality.

I can drop the code from the juju-crashdump script into both matrix and bundletester, but the script is kind of inherently tricky, and I'd rather not be maintaining a tricky, oft patched script in two different places. :-/

**Comment by marcoceppi** [comment]
The general guideance has been, if it requires a set of deps or more complexity than a one off script, it should be it's own project. This is what juju-wait and others have done, I'd recommend this route for this plugin.

**Comment by petevg** [comment]
@marcoceppi That sounds sensible. I will move it into its own space.

**Pull request closed without merging**
